version: '3.8'

services:
  app:
    container_name: todolist-app
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - "8180:8180"
    environment:
      - DATABASE_URL=mysql://user:user@db:3306/todolist
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: mysql:lts
    container_name: todolist-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-net

volumes:
  db-data: {}

networks:
  app-net:
    driver: bridge
