services:
  app:
    build:
      target: dev # pakai stage dev agar ada cargo & cargo-watch
    volumes:
      - .:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/usr/src/app/target
    command: ["cargo", "watch", "-q", "-x", "run"]
    environment:
      - DATABASE_URL=mysql://user:user@db:3306/todolist
      - RUST_LOG=debug
    ports:
      - "8180:8180"
    depends_on:
      - db
    networks:
      - app-net

volumes:
  cargo-cache:
  target-cache:
